project_id = "wutjlluliyrazvdvhgak"

[functions.ai-gateway]
verify_jwt = true

[functions.ai-chat]
verify_jwt = true

[functions.assistant-events]
verify_jwt = true

[functions.transcribe-audio]
verify_jwt = true

[functions.news]
verify_jwt = false

[functions.upcoming-launches]
verify_jwt = false

[functions.live-satellites]
verify_jwt = false
