import { MissionPreset } from "./types";

export const MISSION_PRESETS: MissionPreset[] = [
  {
    name: "LEO - Small Launcher",
    description: "Small launcher to Low Earth Orbit (200 km)",
    mission: {
      targetOrbitAltitude: 200,
      orbitType: "LEO",
      targetInclination: 28.5,
      payloadMass: 250,
      gravityLoss: 1500,
      dragLoss: 200,
      steeringLoss: 200,
      reserveMargin: 10,
    },
    stages: [
      {
        name: "Second Stage",
        ispSeaLevel: 290,
        ispVacuum: 340,
        useVacuumIsp: true,
        propellantMass: 2000,
        structuralMassFraction: 0.06,
        numberOfEngines: 1,
      },
      {
        name: "First Stage",
        ispSeaLevel: 290,
        ispVacuum: 312,
        useVacuumIsp: false,
        propellantMass: 15000,
        structuralMassFraction: 0.08,
        numberOfEngines: 1,
      },
    ],
  },
  {
    name: "LEO - Medium Launcher",
    description: "Medium launcher to Low Earth Orbit (400 km)",
    mission: {
      targetOrbitAltitude: 400,
      orbitType: "LEO",
      targetInclination: 51.6,
      payloadMass: 5000,
      gravityLoss: 1500,
      dragLoss: 200,
      steeringLoss: 200,
      reserveMargin: 10,
    },
    stages: [
      {
        name: "Second Stage",
        ispSeaLevel: 282,
        ispVacuum: 340,
        useVacuumIsp: true,
        propellantMass: 110000,
        structuralMassFraction: 0.06,
        numberOfEngines: 1,
      },
      {
        name: "First Stage",
        ispSeaLevel: 282,
        ispVacuum: 312,
        useVacuumIsp: false,
        propellantMass: 395700,
        structuralMassFraction: 0.08,
        numberOfEngines: 9,
      },
    ],
  },
  {
    name: "GTO Transfer",
    description: "Launch to Geostationary Transfer Orbit",
    mission: {
      targetOrbitAltitude: 200,
      orbitType: "GTO",
      targetInclination: 28.5,
      payloadMass: 5000,
      gravityLoss: 1500,
      dragLoss: 200,
      steeringLoss: 200,
      reserveMargin: 10,
      hohmannTransfer: {
        initialAltitude: 200,
        finalAltitude: 35786,
      },
    },
    stages: [
      {
        name: "Second Stage",
        ispSeaLevel: 282,
        ispVacuum: 340,
        useVacuumIsp: true,
        propellantMass: 110000,
        structuralMassFraction: 0.06,
        numberOfEngines: 1,
      },
      {
        name: "First Stage",
        ispSeaLevel: 282,
        ispVacuum: 312,
        useVacuumIsp: false,
        propellantMass: 395700,
        structuralMassFraction: 0.08,
        numberOfEngines: 9,
      },
    ],
  },
  {
    name: "GEO Circularization",
    description: "Transfer from GTO to Geostationary Orbit",
    mission: {
      targetOrbitAltitude: 35786,
      orbitType: "GEO",
      targetInclination: 0,
      payloadMass: 3000,
      gravityLoss: 0,
      dragLoss: 0,
      steeringLoss: 0,
      reserveMargin: 10,
    },
    stages: [
      {
        name: "Apogee Kick Motor",
        ispSeaLevel: 300,
        ispVacuum: 320,
        useVacuumIsp: true,
        propellantMass: 5000,
        structuralMassFraction: 0.08,
        numberOfEngines: 1,
      },
    ],
  },
  {
    name: "Lunar Transfer",
    description: "Transfer to Moon (Hohmann-like trajectory)",
    mission: {
      targetOrbitAltitude: 200,
      orbitType: "Custom",
      targetInclination: 28.5,
      payloadMass: 1000,
      gravityLoss: 1500,
      dragLoss: 200,
      steeringLoss: 200,
      reserveMargin: 15,
      hohmannTransfer: {
        initialAltitude: 200,
        finalAltitude: 384400, // Moon distance in km
      },
    },
    stages: [
      {
        name: "Trans-Lunar Injection Stage",
        ispSeaLevel: 300,
        ispVacuum: 450,
        useVacuumIsp: true,
        propellantMass: 15000,
        structuralMassFraction: 0.06,
        numberOfEngines: 1,
      },
      {
        name: "Second Stage",
        ispSeaLevel: 290,
        ispVacuum: 340,
        useVacuumIsp: true,
        propellantMass: 20000,
        structuralMassFraction: 0.06,
        numberOfEngines: 1,
      },
      {
        name: "First Stage",
        ispSeaLevel: 290,
        ispVacuum: 312,
        useVacuumIsp: false,
        propellantMass: 150000,
        structuralMassFraction: 0.08,
        numberOfEngines: 9,
      },
    ],
  },
  {
    name: "Mars Transfer",
    description: "Escape Earth and transfer to Mars",
    mission: {
      targetOrbitAltitude: 200,
      orbitType: "Escape",
      targetInclination: 28.5,
      payloadMass: 5000,
      gravityLoss: 1500,
      dragLoss: 200,
      steeringLoss: 200,
      reserveMargin: 20,
    },
    stages: [
      {
        name: "Trans-Mars Injection",
        ispSeaLevel: 300,
        ispVacuum: 450,
        useVacuumIsp: true,
        propellantMass: 50000,
        structuralMassFraction: 0.06,
        numberOfEngines: 1,
      },
      {
        name: "Second Stage",
        ispSeaLevel: 290,
        ispVacuum: 340,
        useVacuumIsp: true,
        propellantMass: 80000,
        structuralMassFraction: 0.06,
        numberOfEngines: 1,
      },
      {
        name: "First Stage",
        ispSeaLevel: 290,
        ispVacuum: 312,
        useVacuumIsp: false,
        propellantMass: 300000,
        structuralMassFraction: 0.08,
        numberOfEngines: 9,
      },
    ],
  },
];

